param(
    [Parameter(Mandatory = $true)][string]$UnityEditor,
    [Parameter(Mandatory = $true)][string]$ProjectPath,
    [Parameter(Mandatory = $true)][string]$UnityVersion,
    [switch]$AllSources,
    [switch]$Package,
    [switch]$BuildPlayer,
    [switch]$Preview,
    [switch]$PlayMode,
    [switch]$RenderPreview
)
$ErrorActionPreference = 'Stop'
$repo = Split-Path $PSScriptRoot -Parent
$project = [IO.Path]::GetFullPath($ProjectPath)
$marker = Join-Path $project '.bird-generated-validation'
if ($AllSources -and $Package) { throw 'Choose either AllSources or Package.' }
if ($BuildPlayer -and !$Package) { throw 'BuildPlayer requires Package mode.' }
if ($Preview -and (!$Package -or $BuildPlayer)) { throw 'Preview requires Package and cannot be combined with BuildPlayer.' }
if ($PlayMode -and !$Preview) { throw 'PlayMode requires Preview.' }
if ($RenderPreview -and !$PlayMode) { throw 'RenderPreview requires PlayMode.' }
$mode = if ($Preview) { 'preview' } elseif ($BuildPlayer) { 'package-player' } elseif ($Package) { 'package' } elseif ($AllSources) { 'all-sources' } else { 'core' }
if ((Test-Path $project) -and !(Test-Path $marker)) {
    throw 'Refusing to modify an existing project without the Bird validation marker.'
}
$modeFile = Join-Path $project '.bird-validation-mode'
if ((Test-Path $marker) -and (Test-Path $modeFile)) {
    if ((Get-Content -Raw $modeFile).Trim() -ne $mode) { throw 'Use a separate project directory for each validation mode.' }
} elseif ((Test-Path $marker) -and ($AllSources -or $Package)) {
    throw 'Use a new project directory for integration validation, not an existing core project.'
}
if (!(Test-Path -LiteralPath $UnityEditor)) { throw 'Unity editor executable not found.' }
New-Item -ItemType Directory -Force $project | Out-Null
Set-Content -LiteralPath $marker -Value 'Generated by tests/Invoke-UnityCoreChecks.ps1; source lives in the package repository.'
Set-Content -LiteralPath $modeFile -Value $mode
foreach ($folder in @('Assets/Editor', 'Assets/BirdCore', 'Packages', 'ProjectSettings')) {
    New-Item -ItemType Directory -Force (Join-Path $project $folder) | Out-Null
}
Set-Content -LiteralPath (Join-Path $project 'ProjectSettings/ProjectVersion.txt') -Value "m_EditorVersion: $UnityVersion"
$manifest = if ($AllSources) { '{"dependencies":{"com.unity.modules.physics":"1.0.0","com.unity.modules.imgui":"1.0.0"}}' } else { '{"dependencies":{}}' }
if ($Package) {
    $packagePath = (Join-Path $repo 'Unity/BirdPlugin').Replace('\', '/')
    $manifest = @{ dependencies = @{ 'com.bird3d.cursor' = "file:$packagePath" } } | ConvertTo-Json -Depth 3
}
if ($Preview) {
    # PNG capture belongs to the validation project, not the distributed package.
    $previewManifest = $manifest | ConvertFrom-Json -AsHashtable
    $previewManifest.dependencies['com.unity.modules.imageconversion'] = '1.0.0'
    $manifest = $previewManifest | ConvertTo-Json -Depth 3
}
Set-Content -LiteralPath (Join-Path $project 'Packages/manifest.json') -Value $manifest
$sourceNames = if ($Package) { @() } elseif ($AllSources) {
    Get-ChildItem -LiteralPath (Join-Path $repo 'Unity/BirdPlugin/Runtime/Scripts') -Filter '*.cs' | ForEach-Object { $_.Name }
} else { @('Hand.cs', 'HandFactory.cs', 'Bird.cs', 'KalmanFilterVector3.cs') }
foreach ($source in $sourceNames) {
    Copy-Item -LiteralPath (Join-Path $repo "Unity/BirdPlugin/Runtime/Scripts/$source") -Destination (Join-Path $project "Assets/BirdCore/$source")
}
if ($AllSources) {
    # Include optional adapters outside the core folder; guards keep SDKs optional.
    Copy-Item -LiteralPath (Join-Path $repo 'Unity/BirdPlugin/Runtime/XRHands/OpenXRHand.cs') -Destination (Join-Path $project 'Assets/BirdCore/OpenXRHand.cs')
    Copy-Item -LiteralPath (Join-Path $repo 'Unity/BirdPlugin/Editor/BirdTrackingConfigureWindow.cs') -Destination (Join-Path $project 'Assets/Editor/BirdTrackingConfigureWindow.cs')
    # Earlier harness versions copied this editor file beside the runtime sources.
    $oldEditorCopy = Join-Path $project 'Assets/BirdCore/BirdTrackingConfigureWindow.cs'
    if (Test-Path $oldEditorCopy) { Remove-Item -LiteralPath $oldEditorCopy }
}
Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'UnityCoreChecks.cs') -Destination (Join-Path $project 'Assets/Editor/UnityCoreChecks.cs')
if ($BuildPlayer) {
    Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'UnityPlayerBuild.cs') -Destination (Join-Path $project 'Assets/Editor/UnityPlayerBuild.cs')
    Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'UnityPlayerSmoke.cs') -Destination (Join-Path $project 'Assets/UnityPlayerSmoke.cs')
}
if ($Preview) {
    Copy-Item -LiteralPath (Join-Path $repo 'Unity/BirdPlugin/Samples~/DesktopPreview/BirdDesktopPreview.cs') -Destination (Join-Path $project 'Assets/BirdDesktopPreview.cs')
    Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'UnityPreviewPlayChecks.cs') -Destination (Join-Path $project 'Assets/UnityPreviewPlayChecks.cs')
    Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'UnityPreviewScene.cs') -Destination (Join-Path $project 'Assets/Editor/UnityPreviewScene.cs')
}
$result = Join-Path $project 'core-checks-result.txt'
# Replace any previous result so an import/license failure cannot appear to pass.
Set-Content -LiteralPath $result -Value 'PENDING: Unity has not completed this run.'
$log = Join-Path $project 'core-checks.log'
$method = if ($PlayMode) { 'UnityPreviewScene.RunPlayChecks' } elseif ($Preview) { 'UnityPreviewScene.Create' } elseif ($BuildPlayer) { 'UnityPlayerBuild.Run' } else { 'UnityCoreChecks.Run' }
$arguments = @('-batchmode', '-nographics', '-projectPath', ('"' + $project + '"'), '-executeMethod', $method, '-logFile', ('"' + $log + '"'))
if ($RenderPreview) {
    $arguments = @($arguments | Where-Object { $_ -ne '-nographics' }) + '-birdRenderPreview'
    foreach ($capture in @('preview-idle.png', 'preview-selected.png', 'preview-lost-pose.png', 'preview-trails.png', 'preview-feedback.png')) {
        $capturePath = Join-Path $project $capture
        if (Test-Path -LiteralPath $capturePath) { Remove-Item -LiteralPath $capturePath }
    }
}
$process = Start-Process -FilePath $UnityEditor -ArgumentList $arguments -WindowStyle Hidden -PassThru
if (!$process.WaitForExit(180000)) {
    $process.Kill()
    throw "Unity exceeded three minutes. See $log"
}
$process.Refresh()
$summary = Get-Content -Raw -LiteralPath $result
Write-Output $summary
$productionSourceCount = $sourceNames.Count + $(if ($AllSources) { 1 } else { 0 })
Write-Output "Compilation mode: $mode ($productionSourceCount production source files)."
if ($process.ExitCode -ne 0 -or !$summary.StartsWith('PASS:')) {
    throw "Unity core checks failed (exit $($process.ExitCode)). See $log"
}
if ($BuildPlayer) {
    $playerResult = Join-Path $project 'player-smoke-result.txt'
    Set-Content -LiteralPath $playerResult -Value 'PENDING: player has not completed this run.'
    $playerLog = Join-Path $project 'player-smoke.log'
    $playerArgs = @('-batchmode', '-nographics', '-birdSmokeResult', ('"' + $playerResult + '"'), '-logFile', ('"' + $playerLog + '"'))
    $player = Start-Process -FilePath (Join-Path $project 'Build/BirdPlayerSmoke.exe') -ArgumentList $playerArgs -WindowStyle Hidden -PassThru
    if (!$player.WaitForExit(30000)) { $player.Kill(); throw "Player timed out. See $playerLog" }
    $player.Refresh()
    $playerSummary = Get-Content -Raw -LiteralPath $playerResult
    Write-Output $playerSummary
    if ($player.ExitCode -ne 0 -or !$playerSummary.StartsWith('PASS:')) { throw "Player smoke test failed. See $playerLog" }
}
