#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;
using UnityEngine.SceneManagement;
using VRC.Core;
using VRC.SDK3.Components;
using VRC.Udon;

// Observe the scene after SDK processing. Never alter it, skip SDK validation,
// upload, or treat successful export as client/physical/multiplayer validation.
public class UnityTrackingLabBuildAudit : IProcessSceneWithReport
{
    const string Folder="../Validation/TrackingLab";
    static bool armed;
    static string[] expectedPrograms;
    static string blueprint;
    static Record record;
    public int callbackOrder => int.MaxValue;

    [Serializable] public class Record
    {
        public int schemaVersion=1;
        public string platform, builtUtc, unityVersion, worldsSdkVersion;
        public string scenePath, sceneGuid, sceneSha256, blueprintId;
        public string artifact, sha256, layoutSha256, runtimeSourcesSha256;
        public long bytes;
        public int processedSceneCount;
        public int gameObjects, components, udonBehaviours, missingScripts, customMonoBehaviours;
        public bool launchRequested, compressedSizeGatePassed, uncompressedSizeGatePassed;
        public string[] sceneCatalog, programs, componentTypes, networkBindings;
        public string evidence="Normal SDK build/error and upload-size gates plus processed-scene structural audit. Not account eligibility, server acceptance, client load, hand fidelity or multiplayer validation.";
    }

    public static void Begin(Scene scene)
    {
        armed=false;
        var pipelines=All<PipelineManager>(scene);
        Require(pipelines.Length==1,"Expected one authored PipelineManager");
        blueprint=pipelines[0].blueprintId??"";
        // Source GUIDs are stable; generated bytecode differs legitimately by platform.
        expectedPrograms=All<UdonBehaviour>(scene).Select(ProgramIdentity).OrderBy(s=>s,StringComparer.Ordinal).ToArray();
        Require(expectedPrograms.Length>0,"Authored lab has no Udon behaviours");
        record=new Record {
            platform=EditorUserBuildSettings.activeBuildTarget==BuildTarget.Android?"Android":"Windows",
            scenePath=UnityTrackingLab.ScenePath, sceneGuid=AssetDatabase.AssetPathToGUID(UnityTrackingLab.ScenePath),
            unityVersion=Application.unityVersion, blueprintId=blueprint,
            runtimeSourcesSha256=RuntimeSourcesHash(),
            worldsSdkVersion=UnityEditor.PackageManager.PackageInfo.FindForAssembly(typeof(VRCSceneDescriptor).Assembly)?.version??"unknown"
        };
        armed=true;
    }
    public static void End() { armed=false; }

    public void OnProcessScene(Scene scene, BuildReport report)
    {
        if(!armed || scene.path!=UnityTrackingLab.ScenePath || EditorApplication.isPlayingOrWillChangePlaymode) return;
        try
        {
            var roots=scene.GetRootGameObjects();
            var components=roots.SelectMany(r=>r.GetComponentsInChildren<Component>(true)).ToArray();
            int missing=components.Count(c=>c==null);
            Require(missing==0,"Processed lab contains missing scripts");
            var scripts=components.OfType<MonoBehaviour>().Where(c=>c.GetType().Assembly.GetName().Name.StartsWith("Assembly-CSharp",StringComparison.Ordinal)).ToArray();
            Require(scripts.Length==0,"Uncompiled project MonoBehaviours survived SDK processing: "+string.Join(", ",scripts.Select(c=>c.GetType().FullName)));
            var descriptors=components.OfType<VRCSceneDescriptor>().ToArray();
            var pipelines=components.OfType<PipelineManager>().ToArray();
            Require(descriptors.Length==1 && pipelines.Length==1,"Processed lab descriptor/pipeline mismatch");
            Require((pipelines[0].blueprintId??"")==blueprint,"Build changed blueprint identity");
            Require(descriptors[0].GetValidatedSpawnList().Count>0,"Processed lab has no spawn");
            var udon=components.OfType<UdonBehaviour>().ToArray();
            var identities=udon.Select(ProgramIdentity).OrderBy(s=>s,StringComparer.Ordinal).ToArray();
            Require(identities.SequenceEqual(expectedPrograms),"SDK export changed/missed authored Udon program bindings");
            foreach(var vm in udon)
            {
                var property=new SerializedObject(vm).FindProperty("serializedProgramAsset");
                var asset=property?.objectReferenceValue as AbstractSerializedUdonProgramAsset;
                Require(asset!=null && asset.RetrieveProgram()!=null && vm.ProgramSize>0,"Missing exported Udon bytecode at "+Hierarchy(vm.transform));
            }
            string layout=Layout(scene);
            Require(record.processedSceneCount==0 || record.layoutSha256==layout,"Repeated scene-processing passes changed lab layout");
            record.processedSceneCount++;
            record.layoutSha256=layout; record.programs=identities;
            record.gameObjects=components.OfType<Transform>().Count(); record.components=components.Length;
            record.udonBehaviours=udon.Length; record.missingScripts=missing; record.customMonoBehaviours=scripts.Length;
            record.componentTypes=components.GroupBy(c=>c.GetType().FullName).OrderBy(g=>g.Key,StringComparer.Ordinal).Select(g=>g.Key+": "+g.Count()).ToArray();
            record.networkBindings=NetworkBindings(descriptors[0]);
        }
        catch(Exception e) { throw new BuildFailedException("Bird lab processed-scene audit: "+e.Message); }
    }

    public static string Complete(string artifact,bool launch)
    {
        Require(armed && record!=null && record.processedSceneCount>0,"SDK did not invoke the processed-scene audit; do not reuse an old record");
        armed=false;
        record.artifact=Path.GetFileName(artifact); record.bytes=new FileInfo(artifact).Length;
        record.sha256=Hash(File.ReadAllBytes(artifact)); record.sceneSha256=Hash(File.ReadAllBytes(UnityTrackingLab.ScenePath));
        record.builtUtc=DateTime.UtcNow.ToString("o"); record.launchRequested=launch;
        record.compressedSizeGatePassed=true; record.uncompressedSizeGatePassed=true;
        var bundle=AssetBundle.LoadFromFile(artifact);
        Require(bundle!=null,"Cannot read built bundle catalog");
        try { record.sceneCatalog=bundle.GetAllScenePaths(); }
        finally { bundle.Unload(true); }
        Require(record.sceneCatalog.Length==1 && record.sceneCatalog[0].Equals(UnityTrackingLab.ScenePath,StringComparison.OrdinalIgnoreCase),"Unexpected lab bundle scene catalog");
        Directory.CreateDirectory(Folder);
        File.WriteAllText(Folder+"/BirdTrackingLab_"+record.platform+".json",JsonUtility.ToJson(record,true));
        return record.udonBehaviours+" compiled Udon behaviours; no missing scripts or project MonoBehaviours in processed scene; bundle catalog verified";
    }

    public static void ComparePlatforms()
    {
        try
        {
            var windows=Read("Windows"); var android=Read("Android");
            Require(windows.platform=="Windows" && android.platform=="Android","Wrong platform records");
            Require(windows.runtimeSourcesSha256==android.runtimeSourcesSha256 && windows.unityVersion==android.unityVersion && windows.worldsSdkVersion==android.worldsSdkVersion,"Source/editor/SDK versions differ across builds");
            Require(android.runtimeSourcesSha256==RuntimeSourcesHash(),"Runtime sources changed since these builds");
            Require(windows.sceneGuid==android.sceneGuid && windows.blueprintId==android.blueprintId,"Platform scene/blueprint identities differ");
            Require(windows.layoutSha256==android.layoutSha256,"Processed scene hierarchy/transforms/colliders/spawns differ across platforms");
            Require(windows.programs.SequenceEqual(android.programs),"Platform Udon bindings differ");
            Require(windows.componentTypes.SequenceEqual(android.componentTypes),"Platform component inventory differs");
            Require(windows.networkBindings.SequenceEqual(android.networkBindings),"Platform network IDs differ");
            UnityTrackingLab.Finish("lab-platforms",true,"Windows/Android source/version, processed scene identity, layout/colliders/spawns, component inventory, network IDs and "+windows.udonBehaviours+" Udon bindings match. Artifact hashes match records. No client launch or online upload implied.");
        }
        catch(Exception e) { UnityTrackingLab.Finish("lab-platforms",false,e.ToString()); }
    }
    static Record Read(string platform)
    {
        var r=JsonUtility.FromJson<Record>(File.ReadAllText(Folder+"/BirdTrackingLab_"+platform+".json"));
        Require(r.schemaVersion==1 && r.processedSceneCount>0,"Invalid build record");
        Require(r.sha256==Hash(File.ReadAllBytes(Folder+"/"+r.artifact)),"Bundle changed since audit: "+platform);
        return r;
    }
    static string ProgramIdentity(UdonBehaviour vm)
    {
        // programSource is editor metadata and remains available during scene processing.
        Require(vm.programSource!=null,"Missing authored Udon source at "+Hierarchy(vm.transform));
        string guid=AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(vm.programSource));
        Require(!string.IsNullOrEmpty(guid),"Udon source is not a saved asset");
        return Hierarchy(vm.transform)+"/Udon["+Array.IndexOf(vm.GetComponents<UdonBehaviour>(),vm)+"]="+guid;
    }
    static string RuntimeSourcesHash()
    {
        // Exclude editor fixtures and generated bytecode; retain source/meta and shaders.
        var paths=Directory.GetFiles("Assets/BirdGenerated/Runtime","Bird*.cs*")
            .Concat(Directory.GetFiles("Assets/BirdGenerated/Presentation","*.shader*")).OrderBy(p=>p,StringComparer.Ordinal);
        return Hash(Encoding.UTF8.GetBytes(string.Join("\n",paths.Select(p=>p.Replace('\\','/')+"="+Hash(File.ReadAllBytes(p))))));
    }
    static string[] NetworkBindings(VRCSceneDescriptor descriptor)
    {
        var property=new SerializedObject(descriptor).FindProperty("NetworkIDs");
        Require(property!=null && property.isArray,"SDK NetworkIDs serialization changed; update the audit");
        var rows=new List<string>(); var ids=new HashSet<int>();
        for(int i=0;i<property.arraySize;i++)
        {
            var item=property.GetArrayElementAtIndex(i);
            var go=item.FindPropertyRelative("gameObject").objectReferenceValue as GameObject;
            int id=item.FindPropertyRelative("ID").intValue;
            Require(go!=null && ids.Add(id),"Missing object or duplicate SDK network ID");
            var types=item.FindPropertyRelative("SerializedTypeNames"); var names=new List<string>();
            for(int j=0;j<types.arraySize;j++) names.Add(types.GetArrayElementAtIndex(j).stringValue);
            rows.Add(id+"|"+Hierarchy(go.transform)+"|"+string.Join(",",names));
        }
        rows.Sort(StringComparer.Ordinal); return rows.ToArray();
    }
    static T[] All<T>(Scene scene) where T:Component { return scene.GetRootGameObjects().SelectMany(r=>r.GetComponentsInChildren<T>(true)).ToArray(); }
    static string Hierarchy(Transform t) { return (t.parent==null?"":Hierarchy(t.parent)+"/")+t.GetSiblingIndex()+":"+t.name; }
    static string Number(float f) { return f.ToString("R",CultureInfo.InvariantCulture); }
    static string Vector(Vector3 v) { return Number(v.x)+","+Number(v.y)+","+Number(v.z); }
    static string Layout(Scene scene)
    {
        var rows=new List<string>();
        foreach(var t in All<Transform>(scene))
        {
            var q=t.localRotation;
            rows.Add(Hierarchy(t)+"|"+t.gameObject.activeSelf+"|"+Vector(t.localPosition)+"|"+Vector(t.localScale)+"|"+Number(q.x)+","+Number(q.y)+","+Number(q.z)+","+Number(q.w));
            foreach(var c in t.GetComponents<Collider>())
            {
                string shape=c is BoxCollider box?Vector(box.center)+"/"+Vector(box.size):c is SphereCollider sphere?Vector(sphere.center)+"/"+Number(sphere.radius):null;
                Require(shape!=null,"Add an explicit layout audit for collider type "+c.GetType().Name);
                rows.Add(Hierarchy(t)+"/"+c.GetType().Name+"|"+c.enabled+"|"+c.isTrigger+"|"+shape);
            }
        }
        foreach(var d in All<VRCSceneDescriptor>(scene)) foreach(var s in d.GetValidatedSpawnList()) rows.Add("Spawn:"+Hierarchy(s));
        rows.Sort(StringComparer.Ordinal); return Hash(Encoding.UTF8.GetBytes(string.Join("\n",rows)));
    }
    static string Hash(byte[] bytes) { using(var sha=SHA256.Create()) return BitConverter.ToString(sha.ComputeHash(bytes)).Replace("-",""); }
    static void Require(bool condition,string message) { if(!condition) throw new Exception(message); }
}
#endif
